import { SxProps, Theme } from "@mui/material";

export const styles: Record<string, SxProps<Theme>> = {
    container: {
        display: 'flex',
        minHeight: '100vh',
        width: '100%',
    },
    leftSide: {
        width: '50%',
        backgroundColor: '#dadaf0',
        display: 'flex',
        flexDirection: 'column',
        padding: '100px 40px 40px 40px',
        position: 'fixed',
        left: 0,
        top: 0,
        bottom: 0,
    },
    logo: {
        maxWidth: '520px',
        height: 'auto',
        marginBottom: '30px',
        display: 'block',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    subtitle: {
        fontSize: '24px',
        fontWeight: 400,
        textAlign: 'center',
    },
    carouselContainer: {
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        margin: '40px 0',
        width: '100%',
        height: '400px',
    },
    carouselImage: {
        maxWidth: '100%',
        height: '100%',
        objectFit: 'contain',
        opacity: 0,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        transition: 'opacity 1.5s ease-in-out',
    },
    carouselIndicators: {
        position: 'absolute',
        bottom: '25px',
        left: '50%',
        transform: 'translateX(-50%)',
        display: 'flex',
        gap: '12px',
        zIndex: 2,
    },
    carouselDot: {
        width: '10px',
        height: '10px',
        borderRadius: '50%',
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        border: 'none',
        cursor: 'pointer',
        padding: 0,
    },
    activeDot: {
        backgroundColor: '#1a237e',
    },
    rightSide: {
        width: '50%',
        backgroundColor: '#F8F8FF',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '100px 40px 40px 40px',
        position: 'fixed',
        right: 0,
        top: 0,
        bottom: 0,
    },
};